### ISSUE TITLE
Support for G533QM

### ISSUE THREAD

**Issue by PSeitz** [Yarn/rog_fan_curve#3]
Support for G533QM would be nice. I tried the same command as  GA401, but it didn't work

```
pascal@pascal-rogstrixg533qmg533qm ~/rog_fan_curve (master) [101]> target/release/rog_fan_curve_cli --board G533QM '30c:50%,49c:50%,59c:50%,69c:50%,79c:50%,89c:50%,99c:50%,109c:50%'
    4 Warning: This fan curve wouldn't be allowed in armoury crate and may be unsafe.
    3 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })', rog_fan_curve_cli/src/main.rs:66:38
    2 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I don't know how I can find out the correct fan address and command.

**Comment by Yarn** [comment]
It looks like you don't have the acpi_call kernel module installed/loaded. Your distro will probably have a package for it. If it's installed correctly `/proc/acpi/call` should exist.

**Comment by Yarn** [comment]
if you install acpi_call and confirm it works (need to use `--board GA401IV`, see readme for the cli) or have other issues re-open this issue or open a new one
