### ISSUE TITLE
Make model names generic

### ISSUE THREAD

**Issue by flukejones** [Yarn/rog_fan_curve#5]
We have pretty concrete information form the last... lots of months that these naming schemes can be reduced down to `GA401I`, `GA401Q` which would enable much easier support of model variants instead of trying to catch and match them all.

https://github.com/Yarn/rog_fan_curve/blob/c01a9a728e61768e4d8caa327fa61ca03421ebcb/rog_fan_curve/src/lib.rs#L309-L316

**Comment by Yarn** [comment]
d3334c83e298eb5ff2bc0163f06c8383d5e0a382

released, version 0.1.10
