### ISSUE TITLE
add support for zephyrus G15 GA502IU-ES76

### ISSUE THREAD

**Issue by Ninjastorm380** [Yarn/rog_fan_curve#7]
Hello! Recently, I did some testing on my own zephyrus laptop using a fork of your repo to see if your utility could control my fans. I can confirm that it functions perfectly if identified as GA401 using --board. Could it be possible to add support?

**Note: I have a PR ready for merge if you do wish to add over at [this link](https://github.com/Yarn/rog_fan_curve/pull/6).

**Comment by Yarn** [comment]
sorry for the slow response, the board is added. thanks for testing

**Comment by Ninjastorm380** [comment]
no problem!
